on:
  # push:
  # pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DavidAnson/markdownlint-cli2-action@v20
        continue-on-error: true
        with:
          globs: |
            *.md
            !test/*.md
          fix: true
