FROM node:12

WORKDIR /usr/src/app/ui

#COPY package*.json ./

#RUN npm ci -g @angular-devkit/build-angular && npm ci

COPY package*.json ./
RUN npm ci

# Додаємо код
COPY . .

# Збірка Angular проєкту (замінити на назву вашого)
RUN npm run build --configuration=production

EXPOSE 4201

CMD ["npm", "start"]
